### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by MagicMuffinBoi** [sneakerhax/PyDorker#1]
Traceback (most recent call last):
  File "C:\Users\Muffin\Desktop\PythonStuff\PyDorker\pydorker.py", line 1, in <module>
    from googlesearch import search
ModuleNotFoundError: No module named 'googlesearch'

is the error that I get when I run the python file. I ran the shell file and it installed the google chrome stuff. Please help.

**Comment by MagicMuffinBoi** [comment]
nvm im just stupid and didnt upgrade python

**Comment by sneakerhax** [comment]
No problem. Didn't know anybody was using this tool I added updated installation instructions and a Dockerfile
